In [1]:
import tensorflow as tf

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

In [2]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1 * w1 + x2 * w2 + x3 * w3

In [3]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hi_val, _ = sess.run([cost,hypothesis,train],
                                   feed_dict={x1:x1_data,x2:x2_data,x3:x3_data,Y:y_data}) 
    if step % 10 == 0:
        print(step, "Cost:", cost_val, "\nPrediction:\n",hi_val)

0 Cost: 19436.426 
Prediction:
 [24.632893 38.001232 33.010017 37.26129  29.986267]
10 Cost: 3.9764454 
Prediction:
 [147.95526 186.21378 179.05309 196.29791 143.03134]
20 Cost: 3.7818894 
Prediction:
 [148.33542 186.65768 179.49728 196.78046 143.36768]
30 Cost: 3.7654407 
Prediction:
 [148.34343 186.65434 179.50076 196.7831  143.36285]
40 Cost: 3.749102 
Prediction:
 [148.35031 186.64969 179.50293 196.7843  143.35706]
50 Cost: 3.732832 
Prediction:
 [148.35716 186.64502 179.50507 196.78546 143.35126]
60 Cost: 3.716658 
Prediction:
 [148.364   186.64038 179.50722 196.78664 143.34547]
70 Cost: 3.70056 
Prediction:
 [148.37082 186.63574 179.50935 196.78781 143.3397 ]
80 Cost: 3.6845672 
Prediction:
 [148.37761 186.63112 179.51149 196.78899 143.33395]
90 Cost: 3.668634 
Prediction:
 [148.3844  186.62651 179.51361 196.79015 143.32822]
100 Cost: 3.6528327 
Prediction:
 [148.39114 186.62192 179.51572 196.79129 143.32251]
110 Cost: 3.6370723 
Prediction:
 [148.39789 186.61732 179.51785 196.79

1220 Cost: 2.3194513 
Prediction:
 [149.04582 186.17728 179.7218  196.8989  142.77376]
1230 Cost: 2.3107295 
Prediction:
 [149.05084 186.17386 179.72339 196.89966 142.76959]
1240 Cost: 2.3020902 
Prediction:
 [149.05585 186.17049 179.72498 196.90045 142.76546]
1250 Cost: 2.2934735 
Prediction:
 [149.06084 186.1671  179.72656 196.90121 142.76132]
1260 Cost: 2.284904 
Prediction:
 [149.06583 186.16373 179.72813 196.90201 142.7572 ]
1270 Cost: 2.2763708 
Prediction:
 [149.0708  186.16037 179.7297  196.90277 142.75308]
1280 Cost: 2.2678905 
Prediction:
 [149.07574 186.157   179.73126 196.90353 142.74896]
1290 Cost: 2.25946 
Prediction:
 [149.08069 186.15366 179.73282 196.9043  142.74489]
1300 Cost: 2.2510872 
Prediction:
 [149.0856  186.15031 179.73438 196.90506 142.74081]
1310 Cost: 2.2427237 
Prediction:
 [149.09052 186.14696 179.73593 196.9058  142.73674]
1320 Cost: 2.234418 
Prediction:
 [149.09543 186.14365 179.73749 196.90657 142.7327 ]
1330 Cost: 2.2261646 
Prediction:
 [149.10031 1